### ISSUE TITLE
Hoe extra gegevens toevoegen

### ISSUE THREAD

**Issue by timothy-debock** [bodemenondergrond/codelijst-bemonsteringsprocedure#1]
` <rdf:Description rdf:about="https://data.bodemenondergrond.vlaanderen.be/id/concept/bemonsteringsprocedure/bam">
    <skos:topConceptOf rdf:resource="https://data.bodemenondergrond.vlaanderen.be/id/conceptscheme/bemonsteringsprocedure"/>
    <skos:prefLabel xml:lang="nl">Compendium BAM</skos:prefLabel>
    <skos:inScheme rdf:resource="https://data.bodemenondergrond.vlaanderen.be/id/conceptscheme/bemonsteringsprocedure"/>
    <dc:identifier>bam</dc:identifier>
    <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
  </rdf:Description>`

Hieraan willen we nog een url toevoegen vb: https://emis.vito.be/nl/erkende-laboratoria/mest-bodem-en-veevoeder-vlm/compendium-bam

op welke manier kan dit?

**Comment by gezever** [comment]
Dag @timothy-debock 
Ik heb de link toegevoegd in een kolom "seeAlso" in de source csv, de mapping van seeAlso op rdfs:seeAlso in de context en het script om de rdf te maken uitgevoerd.
In rdf/xml ziet het er zo uit
  <rdf:Description rdf:about="https://data.bodemenondergrond.vlaanderen.be/id/concept/bemonsteringsprocedure/bam">
    <skos:topConceptOf rdf:resource="https://data.bodemenondergrond.vlaanderen.be/id/conceptscheme/bemonsteringsprocedure"/>
    <skos:prefLabel xml:lang="nl">Compendium BAM</skos:prefLabel>
    <skos:notation>bam</skos:notation>
    <skos:inScheme rdf:resource="https://data.bodemenondergrond.vlaanderen.be/id/conceptscheme/bemonsteringsprocedure"/>
    <dc:identifier>bam</dc:identifier>
    <rdfs:seeAlso rdf:resource="https://emis.vito.be/nl/erkende-laboratoria/mest-bodem-en-veevoeder-vlm/compendium-bam"/>
    <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
  </rdf:Description>
